FROM ubuntu_base import 

MAINTAINER "Oranutan Interactive" "tom.gruner@gmail.com"

# elasticsearch
RUN wget --no-check-certificate  https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.11.tar.gz

RUN tar -xf elasticsearch-0.90.11.tar.gz
RUN rm elasticsearch-0.90.2.tar.gz
 
EXPOSE :9200
 
CMD elasticsearch-0.90.11/bin/elasticsearch -f